modules = {
    application {
//        resource url:'js/application.js'
        resource url:'js/jquery-1.7.2.min.js'
//        resource url:'js/jquery-ui-1.8.21.custom.min.js'
        resource url:'js/bootstrap-transition.js'
//        resource url:'js/bootstrap-alert.js'
        resource url:'js/bootstrap-modal.js'
        resource url:'js/bootstrap-dropdown.js'
//        resource url:'js/bootstrap-scrollspy.js'
        resource url:'js/bootstrap-tab.js'
//        resource url:'js/bootstrap-tooltip.js'
//        resource url:'js/bootstrap-popover.js'
//        resource url:'js/bootstrap-button.js'
//        resource url:'js/bootstrap-collapse.js'
//        resource url:'js/bootstrap-carousel.js'
        resource url:'js/bootstrap-typeahead.js'
//        resource url:'js/bootstrap-tour.js'
//        resource url:'js/jquery.cookie.js'
        resource url:'js/fullcalendar.min.js'
//        resource url:'js/jquery.dataTables.min.js'
        resource url:'js/excanvas.js'
//        resource url:'js/jquery.flot.min.js'
        resource url:'js/jquery.flot.pie.min.js'
//        resource url:'js/jquery.flot.stack.js'
//        resource url:'js/jquery.flot.resize.min.js'
//        resource url:'js/jquery.chosen.min.js'
//        resource url:'js/jquery.uniform.min.js'
        resource url:'js/jquery.colorbox.min.js'
        resource url:'js/jquery.cleditor.min.js'
        resource url:'js/jquery.noty.js'
//        resource url:'js/jquery.elfinder.min.js'
        resource url:'js/jquery.raty.min.js'
        resource url:'js/jquery.iphone.toggle.js'
        resource url:'js/jquery.autogrow-textarea.js'
        resource url:'js/jquery.uploadify-3.1.min.js'
        resource url:'js/jquery.history.js'
//        resource url:'js/charisma.js'
//        resource url:'js/common.js'
//        resource url:'js/jquery.ui.widget.js'
//        resource url:'js/jquery-picklist.js'

    }
}